### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by VCwen123** [AolinFeng/PMP-VVC-TIP2023#6]
作者你好，在你的https://github.com/AolinFeng/PMP-VVC-TIP2023/blob/main/Train_QBD.py里面的函数pre_TrainBD(）函数中，在创建疑问txt文件头的名称时如下代码
    log_dir = os.path.join(out_dir, 'loss.txt')
    with open(log_dir, 'a') as f:
        s = "epoch_loss, epoch_b0_L1_loss, epoch_b1_L1_loss, epoch_b2_L1_loss, val_b2_accu, test_b2_accu\n"
        f.write(s)
最后面的两个名称应该不是准确率这两个名字。从后面的代码中可以看到（如下），名称是不是应该是表示的损失值，而不是准确率
        print("Epoch: %d  Loss: %.6f %.6f %.6f" %(epoch, epoch_loss, val_out_info_list[12], test_out_info_list[12]))
        print("Train L1: [B] %.6f %.6f %.6f [D] %.6f %.6f %.6f" %(epoch_b0_L1_loss, epoch_b1_L1_loss, epoch_b2_L1_loss,
                                                                  epoch_d0_L1_loss, epoch_d1_L1_loss, epoch_d2_L1_loss))
虽然这并不会有很大的影响，但还是希望得到作者您的对这个问题的答复。谢谢

**Comment by AolinFeng** [comment]
I think your concern is correct. The first line written to "log.txt" should be the comment of the following information, but it is not correct. You can ignore that.

**Comment by VCwen123** [comment]
好的谢谢你的回复
