### ISSUE TITLE
some  question

### ISSUE THREAD

**Issue by VCwen123** [AolinFeng/PMP-VVC-TIP2023#7]
作者你好，因为在测试中效果对不上，我想请问在你这篇论文中的数据结果的测试条件是什么呢？比如编码多少帧，编码间隔是多少呢？
同时在inference_QBD推理端的过程中需要保持和VTM中编码间隔一样的呢，比如是在inference_QBD端是将一个序列的partition全部推理出来吗？还是始终按照VTM中的需求保持一致呢？
假如我在VTM端要编码30帧，编码间隔是8的话，inference_QBD是对序列全部推理，还是推理间隔是8呢？
inference_QBD的推理的batchsize大小是256还是400呢？还有在论文中计算时间为什么不包含seqs_block_time时间呢？
希望能得到你的解答谢谢。

**Comment by AolinFeng** [comment]
1. 网络训练带有随机性，重训网络有性能波动属于正常现象，测试条件是ctc条件，编码所有帧，间隔是8。
2. 要编码哪些帧，就推理哪些帧的划分，推理划分的过程和编码过程是独立的，因此可以先于编码进行。
3. 推理过程中的batch size不影响性能，只影响推理时间.
4. seqs_block_time是对输入的帧进行分块（用于送入网络）的时间，这个时间是计入论文中汇报的总编码时间的，但是因为这个时间占比非常小，所以论文中没有分析这部分时间占比。

**Comment by VCwen123** [comment]
好的看到了谢谢
