### ISSUE TITLE
一些问题对于4k序列的性能请教

### ISSUE THREAD

**Issue by VCwen123** [AolinFeng/PMP-VVC-TIP2023#8]
您好作者，我在使用你训练的模型来对序列进行推理并测试了其性能，除了4K序列以外，虽然在我自己的电脑上上面进行测试的其他序列性能上和你的有一定的差距（大抵是硬件和实验环境的原因）但都是在合理的范围之内。但是当我在测试4K序列的时候发现，在time saving 上面有很大的出入。我测试了几组4K序列，如在Tango2  在QP37下面的时间节省只有  百分之40几  ，在FoodMarket Qp 37 下面也只有  百分之50几。因此在4个QP下面的总体平均性能差距较大。

1、我使用的也是全部编码，间隔为8的CTC 测试标准。
2、对于这些10bit的4K序列，在推理时我是使用的ffmpeg 将其转化成8bit 来进行推理的，然后在VTM编码的时候还是使用的10bit的视频进行编码。
可能存在的问题：
我想请问在推理端得到10bit的划分是直接使用推理代码里面的转化（测试过但是bdbr损失很大），还是先用ffmpeg进行转化呢，再使用8bit 的推理代码来进行推理？

因此目前不知到哪里出现了问题，困扰很长时间，希望能得到你的答复。
谢谢！

**Comment by AolinFeng** [comment]
你好，
1. 时间节省跟采用的配置有关，如果选择跳过所有划分，时间节省就和方法本身无关，只跟vtm块划分在总编码的时间占比有关。同时不同QP节省时间会有较大差异，这也是由块划分在总编码时间的占比决定的。根据我们的经验，4K序列的时间节省相比其他分辨率一般是比较多的。
2. 你的推理过程看起来没有问题，我当时应该也是使用ffmpeg进行的10bit到8bit转换。推理代码里边不包含10bit到8bit转换的代码，如果你指的是 import_yuv420()这个函数的话，这个函数只是通过入参设置读取10bit或者8bit的序列，如果读取10bit序列但是强行把入参设置为8bit会出问题。

**Comment by VCwen123** [comment]
你好，谢谢你的回复，我使用的是L1配置。
1、按照你回复的意思，如果我在推理之前就准备好了将10比特的视频转换成8bit视频，那是不是我的推理序列对应的cfg配置文件里面的深度依然是8bit ,同时我将不需要使用关于is10bit这个参数了？
2、还有一个是我注意到在这个推理过程中是推理的无须PS（L3）的时间，那么这对于我只测试L1的推理时间是不利的。把不需要层的推理时间也算进去了。（我尝试让推理只输出一层的划分，但是好像无法应用到VTM中。）
3、对于我的4K时间节省不高，是否会和我是利用8bit视频转化成10bit,而不是10bit转化成8bit的视频编码有关系呢？

**Comment by AolinFeng** [comment]
1. 10bit序列用于真正编码，10bit转换而来的8bit序列用于网络推理出块划分，cfg文件如果指的是编码的cfg，那还是需要指定为10bit，读取的序列不管是8bit还是10bit都要按照实际这个序列是几bit来决定。
2. 配置L0,L1,L2确实不需要推理出完整的划分结构，目前的代码没有实现这个功能。
3. 应该不存在需要从8bit转化为10bit的时候，因为这时候一定会有信息损失，不可能转化为原始的10bit序列。

**Comment by VCwen123** [comment]
你好对于这个第一点还是有点疑惑，我这里指的cfg文件是在推理过程中使用的配置文件，在用10bit转化成8bit视频预测10bit划分的时候是不是下面的这个配置文件中的比特深度是填 8? 填10的话会报错。
![Q](https://github.com/AolinFeng/PMP-VVC-TIP2023/assets/148774031/5077fbc1-13b7-4f34-a0a1-3aa6492359cd)

那么是不是这个参数以及语句也不需要
![Snipaste_2024-01-16_10-08-13](https://github.com/AolinFeng/PMP-VVC-TIP2023/assets/148774031/1089a7bf-000c-4d88-afaf-ba0ecbea1c86)

谢谢

**Comment by AolinFeng** [comment]
这两个部分都是要看你读取的文件是10bit还是8bit，他们都不负责10bit和8bit之间的转换，如果是10bit就要指定为10bit，反之亦然。如果不匹配的话会出现错误。

**Comment by harinitw** [comment]
GOOD MORNING SIR. Please provide these "Train_Luma_QP22_QTdepth_Block8.npy
Train_Luma_QP22_BTdepth_Block16.npy
Train_Luma_QP22_MSdirection_Block16.npy"
Thanks in advance sir.
